//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QnAAspTest {
	
	
	public partial class Index {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl txtquestion;
		
		protected System.Web.UI.HtmlControls.HtmlInputControl txtanswer;
		
		protected System.Web.UI.WebControls.Button btncomplete;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl txtresponse;
	}
}
